### ISSUE TITLE
optimizations cause runtime crash

### ISSUE THREAD

**Issue by raboof** [yogthos/mastodon-bot#59]
Since 9c29c13a847bd9382d44026a43f6f1448ed52844, mastodon-bot crashes on me:

```
[:app] Compiling ...
[:app] Build completed. (83 files, 0 compiled, 0 warnings, 11.40s)
/home/aengelen/dev/mastodon-bot/mastodon-bot.js:78
function B(a){if(null==a)return null;if(null!=a&&(a.h&8388608||l===a.ke))return a.ea(null);if(dc(a)||"string"===typeof a)return 0===a.length?null:new ce(a,0,null);if(kc(id,a))return jd(a);throw Error([p.a(a)," is not ISeqable"].join(""));}function C(a){if(null==a)return null;if(null!=a&&(a.h&64||l===a.N))return a.Ka(null);a=B(a);return null==a?null:Hc(a)}function de(a){return null!=a?null!=a&&(a.h&64||l===a.N)?a.Oa(null):(a=B(a))?a.Oa(null):ee:ee}
                                                                                                                                                                                            ^

Error: [object Object] is not ISeqable
    at B (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:78:195)
    at /home/aengelen/dev/mastodon-bot/mastodon-bot.js:205:56
    at pg (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:152:54)
    at og.k.ea (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:154:302)
    at B (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:78:83)
    at Bj (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:364:305)
    at g (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:390:194)
    at /home/aengelen/dev/mastodon-bot/mastodon-bot.js:390:399
    at te (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:84:275)
    at uc (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:129:80)
```

**Comment by raboof** [comment]
on current master (3de9416ed6735dafd4041f0d207fb4362ac9fb7f) the error is different, but still problematic:

```
/home/aengelen/dev/mastodon-bot/mastodon-bot.js:31
var Rc=function Rc(a,b){if(null!=a&&null!=a.tb)return a.tb(a,b);var d=Rc[Ja(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=Rc._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw mc("IMap.-dissoc",a);},Sc=function Sc(a){if(null!=a&&null!=a.Pe)return a.key;var c=Sc[Ja(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=Sc._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw mc("IMapEntry.-key",a);},Tc=function Tc(a){if(null!=a&&null!=a.Qe)return a.v;var c=Tc[Ja(null==
                                                                                                                                                                                                                                                                                                                                                                                                                   ^

Error: No protocol method IMapEntry.-key defined for type object: [object Object]
    at mc (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:21:251)
    at Sc (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:31:410)
    at g (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:390:223)
    at /home/aengelen/dev/mastodon-bot/mastodon-bot.js:390:399
    at te (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:84:275)
    at uc (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:129:80)
    at g (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:390:344)
    at /home/aengelen/dev/mastodon-bot/mastodon-bot.js:390:399
    at te (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:84:275)
    at uc (/home/aengelen/dev/mastodon-bot/mastodon-bot.js:129:80)
```

**Comment by jerger** [comment]
> > ```
> > * #59 - optimizations cause runtime crash
> > ```
> 
> I don't think I can be of actual use there, but I'm happy to test at least ;)

Testing is fine :-)
As your PR is merged should we retry optimization & find the root of this issue?

**Comment by raboof** [comment]
> > > ```
> > > * #59 - optimizations cause runtime crash
> > > ```
> > 
> > 
> > I don't think I can be of actual use there, but I'm happy to test at least ;)
> 
> Testing is fine :-)
> As your PR is merged should we retry optimization & find the root of this issue?

Yeah, if we enable it again on a branch I can share the versions of things I use, the generated code and the stack trace where it fails, so we can narrow this down.

**Comment by jerger** [comment]
tracked the issue down (and read the doc & talked to some js colleagues ;).
Advanced optimizations are shaking the tree (removing unused code). That's definitely not a good idea for node-libs.

For a node-app it may be a valid idea so I tried it out here: 
https://gitlab.com/yogthos/mastodon-bot/-/merge_requests/10

At least `mastodon-bot -h` is working but I do not know whether someone will use mastodon-bot as lib also. For your tests you can use the advanced optimized version `mastodon-bot@1.10.5-20210312125932`  ...

What do you think about?

**Comment by raboof** [comment]
> I do not know whether someone will use mastodon-bot as lib also

I don't expect so. If someone appears who wants that, I think we should probably extract the parts that they're interested in into a lib separate from the `mastodon-bot` app.

> For a node-app it may be a valid idea

If it works it would be great!

> I tried it out here: https://gitlab.com/yogthos/mastodon-bot/-/merge_requests/10 . At least `mastodon-bot -h` is working

`mastodon-bot -h` is not really sufficient: I just tried 3de9416 again, and `mastodon-bot -h` works fine, but actually running it with a configuration produces `Error: [object Object] is not ISeqable`.

I tested your branch, and while 746d726 (the commit before your change) is still OK, on HEAD of the branch I see the problem again:

```
$ MASTODON_BOT_CREDENTIALS=~/dev/mastodon-bot/hack42-credentials.edn node target/mastodon-bot.js ~/dev/mastodon-bot/hack42.edn 
/tmp/mastodon-bot/target/mastodon-bot.js:82
function B(a){if(null==a)return null;if(null!=a&&(a.h&8388608||l===a.me))return a.ea(null);if(kc(a)||"string"===typeof a)return 0===a.length?null:new oe(a,0,null);if(null!=a&&null!=a[wc])return a=cb(a,wc).call(a),pe.a?pe.a(a):pe.call(null,a);if(sc(ud,a))return vd(a);throw Error([q.a(a)," is not ISeqable"].join(""));}function C(a){if(null==a)return null;if(null!=a&&(a.h&64||l===a.T))return a.Ja(null);a=B(a);return null==a?null:Qc(a)}
                                                                                                                                                                                                                                                                           ^

Error: [object Object] is not ISeqable
    at B (/tmp/mastodon-bot/target/mastodon-bot.js:82:274)
    at We (/tmp/mastodon-bot/target/mastodon-bot.js:132:26)
    at Bc (/tmp/mastodon-bot/target/mastodon-bot.js:134:155)
    at ag (/tmp/mastodon-bot/target/mastodon-bot.js:134:286)
    at Function.Ih.c (/tmp/mastodon-bot/target/mastodon-bot.js:229:200)
    at g (/tmp/mastodon-bot/target/mastodon-bot.js:396:249)
    at /tmp/mastodon-bot/target/mastodon-bot.js:396:399
    at Ie (/tmp/mastodon-bot/target/mastodon-bot.js:89:275)
    at Bc (/tmp/mastodon-bot/target/mastodon-bot.js:134:80)
    at g (/tmp/mastodon-bot/target/mastodon-bot.js:396:344)
```

If it's any use, the configuration I'm using is the one at https://github.com/raboof/mastodon-bot-nix/blob/master/hack42.edn . For obvious reasons that repo doesn't include the twitter and mastodon tokens/keys.

This is with npm/npx 6.14.11 and node v14.16.0, not sure if there's any other relevant versions?

**Comment by jerger** [comment]
Then let's continue with optimization simple :-)
