### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by localteampartners** [yogthos/mastodon-bot#73]
When running Mastodon-bot I get this error:

Error: Unexpected EOF while reading item 1 of vector.

Using rss source

**Comment by jerger** [comment]
any idea how to trace this issue down?

**Comment by jerger** [comment]
we improved error-handling & outputs. If the issue is still valid pls. reopen,

**Comment by krv00** [comment]
I have the same problem, in this case, using Twitter feed, when running "**config.edn**": 

```
/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:4883
e,d):f.call(null,a,e,d);if(g!==a)return g}else return cljs.tools.reader.edn.read_symbol(a,e)}}}catch(h){if(h instanceof Error){b=h;if(cljs.tools.reader.impl.utils.ex_info_QMARK_(b)){c=cljs.core.ex_data(b);if(cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(cljs$cst$keyword$reader_DASH_exception,cljs$cst$keyword$type.cljs$core$IFn$_invoke$arity$1(c)))throw b;throw cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3(b.message,cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.PersistentArrayMap(null,
                                                                                                                                                                                                                                                                                                                                                            ^
Error: Unexpected EOF while reading item 1 of vector.
    at new cljs.core.ExceptionInfo (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:2280:47)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:2283:72)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:2282:449)
    at Function.cljs.tools.reader.impl.errors.throw_ex.cljs$core$IFn$_invoke$arity$variadic (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:4651:195)
    at Function.cljs.tools.reader.impl.errors.eof_error.cljs$core$IFn$_invoke$arity$variadic (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:4658:138)
    at Function.cljs.tools.reader.impl.errors.throw_eof_delimited.cljs$core$IFn$_invoke$arity$5 (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:4662:148)
    at Object.cljs.tools.reader.edn.read_delimited (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:4848:498)
    at cljs.tools.reader.edn.read_vector (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:4851:317)
    at Object.cljs.tools.reader.edn.read_delimited (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:4849:418)
    at cljs.tools.reader.edn.read_map (/usr/local/lib/node_modules/mastodon-bot/mastodon-bot.js:4852:238)
```
What could be the cause?

**Comment by jerger** [comment]
I would assume this problem results on broken transmission over network.

After getting the response from twitter api we transform the response to internal datastructure (https://gitlab.com/yogthos/mastodon-bot/-/blob/master/src/main/cljs/mastodon_bot/transform.cljs#L62). The error message intends there are some characters missing. In result this tweet will not be send to mastodon.

If you use the latest release only one tweet should be affected by this exception.
